urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^newtest/$', views.newtest, name='newtest'),
]


# urlpatterns = [
#     url(r'^$', views.home, name='home'),
#     url(r'^newtest/$', views.testsCreateView, name='newtest'),
#     url(r'^modifytest/$', views.testsUpdateView, name='modifytest'),

# ]

models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models

# Create your models here.


TYPE_CHOICES = (
    ('vsCntrl', 'vsCntrl'),
    ('Other', 'Other'),
)

TEST_TYPE_CHOICES = (
    ('T&L', 'T&L'),
    ('Other', 'Other'),
)

MERCH_GROUP_CHOICES =(
    ('Health Care', 'Health Care'),
    ('Consumables', 'Consumables'),
    ('Beauty/Personal', 'Beauty/Personal'),
    ('General Merchandising', 'General Merchandising'),
)

SUCCESS_METRIC_CHOICES = (
    ('Sales Lift', 'Sales Lift'),
    ('Other', 'Other'),
)

class Test(models.Model):
    test_no	= models.IntegerField(primary_key=True)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES)
    test_name = models.CharField(max_length=100)
    test_desc = models.CharField(max_length=250)	
    sponsor = models.CharField(max_length=50)
    merch_group = models.CharField(max_length=50, choices=MERCH_GROUP_CHOICES)
    success_metric = models.CharField(max_length=50, choices=SUCCESS_METRIC_CHOICES)
    success_desc = models.CharField(max_length=100)
    success_value	= models.IntegerField(default=0)
    test_type = models.CharField(max_length=50, choices=TEST_TYPE_CHOICES)



class Store(models.Model):
    test_no = models.IntegerField()
    location_id = models.IntegerField()
    test_store = models.BooleanField(default=0)
    pair = models.IntegerField()



class WaveDate(models.Model):
    test_no = models.IntegerField()
    wave_no = models.IntegerField()
    wave_value = models.CharField(max_length=100)
    pre_start = models.DateField()
    pre_end = models.DateField()
    post_start = models.DateField()
    post_end = models.DateField()



class Product(models.Model):
    test_no = models.IntegerField()
    product_no = models.IntegerField()
    product_level_no = models.IntegerField()
    product_tier = models.IntegerField()
    group_no = models.IntegerField()

forms.py
#from django.forms import forms, ModelForm
from django import forms
from .models import Test, WaveDate



class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = '__all__'


class WaveDateForm(forms.ModelForm):
	class Meta:
		model = WaveDate
		exclude = ['test_no']


SUPER_CATEGORY_CHOICES = (
	(1, 'CONSUMER HEALTH CARE'),
	(2, 'BEAUTY CARE'),
	(3, 'GENERAL MERCHANDISE'),
	(4, 'EDIBLES'),
	(5, 'GREETING CARDS'),
	(6, 'PHOTO'),
	(7, 'PERSONAL CARE'),
)



class ProductForm(forms.Form):
	super_category = forms.MultipleChoiceField(label='Super Category', choices=SUPER_CATEGORY_CHOICES)
	category = forms.IntegerField(label='Category')
	sub_category = forms.IntegerField(label='Sub Category')
   	segment = forms.IntegerField(label='Segment')


class StoreForm(forms.Form):
	store_list = forms.FileField()

views.py
import os
import csv

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import UpdateView, DetailView, ListView

from .models import Test, WaveDate, Product, Store
from .forms import TestForm, WaveDateForm, ProductForm, StoreForm


# Create your views here.

def home(request):
    #context = {'latest_question_list': latest_question_list}
    return render(request, 'tl/home.html')


class IndexView(ListView):
    template_name = 'tl/index.html'
    model = Test


class DetailView(DetailView):
    model = Test
    template_name = 'tl/detail.html'


# class TestUpdate(UpdateView):
#     model = Test
#     template_name = 'tl/UpdateTest.html'



def newtest(request):
    if request.method == 'POST':
        test_form = TestForm(request.POST)
        wavedate_form = WaveDateForm(request.POST)
        product_form = ProductForm(request.POST)
        store_form = StoreForm(request.POST, request.FILES) 

        if test_form.is_valid() and wavedate_form.is_valid() and product_form.is_valid() and store_form.is_valid():
            test = test_form.save()
            test.save()

            wave = wavedate_form.save(commit=False)
            wave.test_no = test.test_no
            wave.save()

            super_category_list = product_form.cleaned_data['super_category']
            for i in super_category_list:
                p1 = Product(test_no=test.test_no, product_no=i, product_level_no=2,product_tier=1, group_no=1)
                p1.save()

            category = product_form.cleaned_data['category']
            p2 = Product(test_no=test.test_no, product_no=category, product_level_no=3,product_tier=1, group_no=1)
            p2.save()

            sub_category = product_form.cleaned_data['sub_category']
            p3 = Product(test_no=test.test_no, product_no=sub_category, product_level_no=4,product_tier=1, group_no=1)
            p3.save()

            segment = product_form.cleaned_data['segment']
            p4 = Product(test_no=test.test_no, product_no=segment, product_level_no=5,product_tier=1, group_no=1)
            p4.save()

            store_list = store_form.cleaned_data['store_list']
            data = csv.DictReader(store_list)
            for row in data:
                Store.objects.create(
                test_no=test.test_no,
                location_id=row['location_id'],
                test_store=row['test_store'],
                pair=row['pair'])
    else:
        test_form = TestForm()
        wavedate_form = WaveDateForm()
        product_form = ProductForm()
        store_form = StoreForm() 

    return render(request, 'tl/newtest.html', {'test_form': test_form, 'wavedate_form': wavedate_form, 'product_form': product_form, 'store_form': store_form})

templates/tl/UpdateTest.html
Hello

<!-- <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form> -->

templates/tl/base.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'tl/bootstrap.css' %}" />
<link rel="stylesheet" href="{% static 'tl/style.css' %}" />



<html lang="en">

	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Brand</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
	        <li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">One more separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	      <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	          </ul>
	        </li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>



	<head>
	    <title>CVS Test & Learn</title>
	</head>
	<body>
		<div class="container-fluid">
			<div class="row"> 
				<div class="col-md-2">
					<img src="/static/tl/images/cvs_health_reg_img.png" class="img-responsive">
				</div> 		
				<div class="col-md-10 text-right text-uppercase">
					<h1>Test & Learn</h1>
					<h4>Data Management</h4>
				</div>	
				<div class="row">
					<div class="col-md-12">
						<hr>
					</div>	
				</div>	
			</div>
			{% block content %}
            {% endblock %}
		</div>
	</body>	

templates/tl/detail.html
{% extends 'tl/base.html' %}


{% block content %}


<p>{{ test.test_no }}</p>
<p>{{ test.test_name }}</p>
<p>{{ test.sponsor }}</p>



{% endblock %}

templates/tl/home.html
{% extends 'tl/base.html' %}



{% block content %}

<div class="row">
	<div class="col-md-12">
		<p>This will be an informational paragraph with instructions. Not Sure what this space will contain!!!!</p>
	</div>	
</div>	
<div class="row">
	<div class="col-md-3">
		<a class="btn btn-default" href="http://localhost:8000/tl/newtest/" role="button"> Create a New Test</a>
	</div>
	<div class="col-md-9">
		<p>Informational paragraph</p>
	</div>	
</div>
<div class="row">
	<div class="col-md-3">
		<a class="btn btn-default" href="http://localhost:8000/tl/updatetest/" role="button"> Update an Existing Test</a>					
	</div>
	<div class="col-md-9">
		<p>Informational paragraph</p>
	</div>	
</div>
<div class="row">
	<div class="col-md-3">
		<h4>Other</h4>					
	</div>
	<div class="col-md-9">
		<p>Informational paragraph</p>					
	</div>	
</div>


{% endblock %}

templates/tl/index.html
{% extends 'tl/base.html' %}

{% block content %}

</div>	
<div class="row">
	<div class="col-md-3">
		<a class="btn btn-default" href="http://localhost:8000/tl/newtest/" role="button"> Create a New Test</a>
	</div>
	<div class="col-md-9">
		<p>Informational paragraph</p>
	</div>	
</div>

<h3> Existing Tests </h3>

<ul>
{% for test in test_list %}
    <li><a href='{% url "tl:detail" test.pk %}'>{{ test.test_no }}</a></li>
{% endfor %}
</ul>

{% endblock %}

templates/tl/newtest.html
{% extends 'tl/base.html' %}

{% block content %}


<form enctype="multipart/form-data" method="POST" class="post-form"> {% csrf_token %}
	<h4>Test Parameters</h4>

	{% for field in test_form %}
    <div class="fieldWrapper">
        {{ field.label }}
        {{ field }}
    </div>
    {% endfor %}

  	<h4>Dates</h4>
	{{ wavedate_form }}

 	<h4>Products</h4>
	{{ product_form }}

 	<h4>Stores</h4>
	{{ store_form }}
	<button type="submit" class="save btn btn-default"> Save </button>
</form>


{% endblock %}